homeassistant:
  # Name of the location where Home Assistant is running
  name: Kyrkjevegen 5
  # Location required to calculate the time the sun rises and sets
  latitude: 61.2255604
  longitude: 7.0982758
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

logger:
  #default: info
  
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  base_url: eide.duckdns.org:443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some dligevices automatically
discovery:
  enable:
    - homekit
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

#Enable recording into database
recorder:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
     - temperature
     - symbol
     - precipitation
     - cloudiness
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: last_boot
      
fastdotcom:
  scan_interval:
    minutes: 30
# Cloud
cloud:

python_script:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Voice and image ffmpeg
#ffmpeg:

#z-wave
zwave:
  usb_path: /dev/ttyACM0
  
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret username
  password: !secret http_password
  max_retries: 3
  default_measurement: state
 
# Thermostats:
input_number:
  livingroom_temp:
    name: Living Room Temperature
    min: 16
    max: 26
    step: 0.5
    mode: slider
    unit_of_measurement: C  
    icon: mdi:target
  office_temp:
    name: Office Temperature
    min: 16
    max: 26
    step: 0.5
    mode: slider
    unit_of_measurement: C  
    icon: mdi:target
  away_temp:
    name: Away Temperature
    min: 16
    max: 26
    step: 1.0
    mode: slider
    unit_of_measurement: C  
    icon: mdi:target
    
climate:
  - platform: generic_thermostat
    name: Livingroom
    heater: switch.heater_livingroom
    target_sensor: sensor.temp_livingroom
    target_temp: 23
    away_temp: 15
    keep_alive: 480
    precision: 0.1
  - platform: generic_thermostat
    name: Office
    heater: switch.heater_office
    target_sensor: sensor.temp_office
    target_temp: 23
    away_temp: 15
    keep_alive: 480
    precision: 0.1

### TIBBER
tibber:
  access_token: !secret tibber_token 

### Online and reboot
binary_sensor:
  - platform: command_line
    command: 'ping -c 1 8.8.8.8 | grep "1 packets received" | wc -l'
    name: 'is_hassio_online'
    payload_on: 1
    payload_off: 0

shell_command:
  restart_pi: reboot
  
### DEVICE TRACKING ###

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-120
    interval_seconds: 60
    
lovelace:
  mode: yaml
  
shopping_list:

## IFRAMES

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: https://hassio.local:8888
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: https://hassio.local:3000

system_health:

mqtt:
  broker: m24.cloudmqtt.com
  port: 27724
  username: !secret CLOUDMQTT_USER
  password: !secret CLOUDMQTT_PASSWORD
  certificate: auto
  
camera:
- platform: mjpeg
  mjpeg_url: http://217.17.213.66:8081/mjpg/video.mjpg?overview=0&camera=1&videoframeskipmode=empty&Axis-Orig-Sw=true&resolution=1280x720